### ISSUE TITLE
Enums generations issue

### ISSUE THREAD

**Issue by Achraf-cyber** [mmvergara/supadart#113]
Since the last update, enums aren't generated at all. But other generated classes still depend on them.

**Comment by mmvergara** [comment]
> Since the last update, enums aren't generated at all. But other generated classes still depend on them.

@Achraf-cyber  You might need to specify your enums on supadart.yaml config file, i recommend trying to generate the `supadart.yaml` again. let me know if you already have it set and still doesn't work

The reason https://github.com/mmvergara/supadart/issues/108

tldr: there was an issue about enum array type generation `enum[]` and due to the swagger api limitations we need to specify them, you can read the issue for more info.

Im gonna keep this issue open and reimplement the functionality of generating the enums if the schema doesn't use `enum[]`

I recommend specifying them in the yaml file for future proofing

**Comment by Achraf-cyber** [comment]
How do I specify the enums in the supadart.yaml file ?

**Comment by mmvergara** [comment]
> How do I specify the enums in the supadart.yaml file ?

ahh year sry, you can do it like this. it's case sensitve.
```dart
# Do you have enums in your database? map them here
enums:
  # mood: [happy, sad, neutral, excited, angry]
  # usergroup: [USERS, ADMIN, MODERATOR]
  ```
   i recommend also to lowercase the enum values to follow dart conventios

**Comment by BeezBeez** [comment]
Hey ! Thank you for this update !
Can we add this part about how to configure enum in the readme file ?

**Comment by mmvergara** [comment]
> Hey ! Thank you for this update ! Can we add this part about how to configure enum in the readme file ?

Will do!, thanks

**Comment by mmvergara** [comment]
> Im gonna keep this issue open and reimplement the functionality of generating the enums if the schema doesn't use enum[]

I did some thinking and just decided to not implement this, i think it's better to just be explicit about the enums and it's not like we always add/change database enum for it to become cumbersome. instead i just improve the documentation for it.

**Comment by mmvergara** [comment]
Closing this if no further queries
