### ISSUE TITLE
Suggested type safe api

### ISSUE THREAD

**Issue by North101** [mmvergara/supadart#95]
I think Supadart could generate better type safe code by creating a wrapper for Supabase instead of adding to it.

current:
```dart
supabase.my_table
  .select()
  .eq(MyTable.c_id, id)
  .single()
  .withConverter(MyTable.converterSingle);

supabase.my_table
  .stream(primaryKeys: [MyTable.c_id])
  .eq(MyTable.c_id, id)
  .map(MyTable.converter);
```

suggested:
```dart
supadart(supabase).myTable
  .select([
    MyTable.c.id, // only allows table columns
  ])
  .where(MyTable.c.id.eq(id)) // type safe filtering
  .single()
  ;// no need to apply a converter

supadart(supabase).myTable
  .stream // primary keys are known to supadart so no need to manually supply them
  .where(MyTable.c.id.eq(id)) // type safe filtering
  ;// no need to apply a converter
```

**Comment by mmvergara** [comment]
Hey, thanks for opening an issue. I like the idea first of all and given it some thought and sample implementations. I've shared it with some of my flutter friends.

They said that the idea was something but probably not going to use it since the normal sdk way is the one they are used to and is really just enough for them. It changed how i think about it, supadart was designed just to add typesafe'ish since its really just the one missing compare to the js sdk. Thanks for suggesting but i think we just stick as much to the  vanilla way.

**Comment by North101** [comment]
Understood. I can also see it being a lot more complex to implement. I might try implementing it myself
